# permissions for end users to edit peers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: peer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: router-operator
    app.kubernetes.io/part-of: router-operator
    app.kubernetes.io/managed-by: kustomize
  name: peer-editor-role
rules:
- apiGroups:
  - routing.lf-net.org
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routing.lf-net.org
  resources:
  - peers/status
  verbs:
  - get
