# permissions for end users to view routers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: router-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: router-operator
    app.kubernetes.io/part-of: router-operator
    app.kubernetes.io/managed-by: kustomize
  name: router-viewer-role
rules:
- apiGroups:
  - routing.lf-net.org
  resources:
  - routers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routing.lf-net.org
  resources:
  - routers/status
  verbs:
  - get
