apiVersion: routing.lf-net.org/v1alpha1
kind: Router
metadata:
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router-sample
    app.kubernetes.io/part-of: router-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: router-operator
  name: router-sample
spec:
  nodeSelector:
    kubernetes.io/hostname: mistral
  tolerations:
  - key: sea-computing.0x0a.network/node-usage
    value: router
    effect: NoSchedule
  nodeID:
    id: 194.28.99.188
